language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential python-dev python3-dev

install:
  - pip install cython

before_script: cd bindings/python
script: python setup.py test